<template>
<Modal :show="open" source="crn" size="small">
  <template #title>
    <span>
      Generate CRN
    </span>
  </template>

  <template #body>
    <div class="flex items-center space-x-8 mt-2">
      <dl>
        <dt class="font-bold text-sm">CRN Date</dt>
        <dd class="text-xs">June 15, 2022</dd>
      </dl>
      <dl>
        <dt class="font-bold text-sm">Generated By:</dt>
        <dd class="text-xs">Moses Kamau</dd>
      </dl>
      <dl>
        <dt class="font-bold text-sm">CRN Amount</dt>
        <dd class="text-xs">KES 205,292.00</dd>
      </dl>
    </div>
    <div class="mt-8">
      <h5 class="font-bold">Assign amounts to selected invoices</h5>
      <p class="text-xs">
        If you do need to <b>specify an amount</b> for certain invoices, you can do so in the form below before downloading
      </p>

      <form v-if="selection.selection.length > 0" class="mt-4 mb-20 px-3 max-h-64 overflow-y-auto">
        <div class="space-y-6 sm:space-y-5">
          <div v-for="ind in 5">
            <label class="flex flex-row space-x-2 text-sm font-medium sm:mt-px sm:pt-2">
              <span>Invoice #909302323</span>
              <small class="text-xs font-light">(KES 45,000.00)</small>
            </label>
            <div class="mt-1 sm:mt-0 sm:col-span-2">
              <input type="text" class="max-w-lg block w-full shadow-sm focus:ring-green-500 focus:border-green-500 sm:max-w-xs sm:text-sm border-gray-300 rounded-md dark:bg-churpy-night dark:border-gray-500" />

              <div class="relative flex items-start mt-2">
              <div class="flex items-center h-5">
                <input id="comments" aria-describedby="comments-description" name="comments" type="checkbox" class="focus:ring-green-500 h-4 w-4 text-churpy-green border-gray-300 rounded dark:bg-churpy-night dark:border-gray-500" />
              </div>
              <div class="ml-3 text-sm">
                <label for="comments" class="font-medium">Set full amount?</label>
              </div>
            </div>

            </div>
          </div>

        </div>
      </form>
      <Alert variant="danger" v-else>
        <b>No invoices selected!</b>
      </Alert>
    </div>
  </template>

  <template #footer>
    <div class="flex space-x-5">
      <c-button variant="danger">Cancel</c-button>
      <c-button variant="success">
        <i class="fa-solid fa-download mr-2"></i>
        Generate
      </c-button>
    </div>
  </template>
</Modal>
</template>

<script>
import Modal from "@/components/page/Modal.vue";
import CButton from "@/components/parts/CButton.vue";
import {inject} from "vue";
import Alert from "@/components/parts/Alert.vue";

export default {
  name: "GenerateCrn",
  emits:['close'],
  props:{
    open:{required: true, type: Boolean},
    selection:{required: true, type: Object},
  },
  components:{
    Alert,
    Modal, CButton
  },
  setup(props, {emit}){

    const emitter = inject('emitter')
     emitter.on('close_modal', (modal_source)=>{
      if (modal_source === 'crn'){
          emit('close')
      }
    })
  }
}
</script>

<style scoped>

</style>